Repository ctc-uci/lpa, pull requests merged in 2025-04, with the labels that each got.

#105 99 keep me signed in protected routes login flow hi fi
  client/index.html
  client/src/App.jsx
  client/src/components/ProtectedRoute.tsx
  client/src/components/forgotpassword/ForgotPassword.css
  client/src/components/forgotpassword/ForgotPassword.jsx
  client/src/components/forgotpassword/ForgotPasswordSent.jsx
  client/src/components/login/Login.css
  client/src/components/login/Login.jsx
  client/src/components/resetpassword/ResetPassword.jsx
  client/src/components/resetpassword/ResetPasswordSuccess.jsx
  client/src/components/signup/Signup.css
  client/src/components/signup/Signup.jsx
  client/src/components/signup/SignupRequested.css
  client/src/components/signup/SignupRequested.jsx
  client/src/contexts/AuthContext.tsx
Labels: Fix Ready

#106 104 email flow and modal
  client/src/assets/BackArrowIcon.jsx
  client/src/assets/EnvelopeIcon.jsx
  client/src/assets/IoPaperPlane.svg
  client/src/assets/icons/emailIcon.svg
  client/src/components/email/ConfirmEmailModal.jsx
  client/src/components/email/DiscardEmailModal.jsx
  client/src/components/email/EmailSidebar.jsx
  client/src/components/invoices/EditInvoice.jsx
  client/src/components/programs/programComponents/ArtistsDropdown.jsx
  client/src/components/programs/programComponents/PayeesDropdown.jsx
  server/routes/email.js
Labels: Looks Good

#108 100 single invoice and component improvements
  client/src/App.jsx
  client/src/assets/DarkPlusIcon.jsx
  client/src/assets/PlusIcon.jsx
  client/src/assets/icons/ProgramIcons.jsx
  client/src/components/invoices/EditInvoiceComponents.jsx
  client/src/components/invoices/EmailHistory.jsx
  client/src/components/invoices/InvoiceComponents.jsx
  client/src/components/invoices/InvoiceView.jsx
  client/src/components/invoices/PDFButtonInvoice.jsx
  client/src/components/invoices/SavedEditInvoiceComponent.jsx
  client/src/components/invoices/SavedEditsInvoice.jsx
  client/src/components/invoices/SingleInvoice.jsx
  client/src/components/navbar/NavBarButton.jsx
  client/src/components/navbar/Navbar.jsx
Labels: bug

#126 118 match high fi notif nav
  client/src/assets/CalendarSelected.jsx
  client/src/assets/InvoiceSelected.jsx
  client/src/components/filters/DateFilter.jsx
  client/src/components/filters/ProgramFilter.jsx
  client/src/components/filters/Sorting.css
  client/src/components/navbar/NavBarButton.jsx
  client/src/components/navbar/Navbar.css
  client/src/components/navbar/Navbar.jsx
  client/src/components/notifications/CalendarIcon.jsx
  client/src/components/notifications/FilterButton.jsx
  client/src/components/notifications/InfoTooltip.jsx
  client/src/components/notifications/Notifications.jsx
  client/src/components/notifications/Notifications.module.css
  client/src/components/notifications/NotificationsComponents.jsx
  client/src/components/programs/Program.jsx
Labels: Fix Needed

#127 115 sessions select implement waive fees payment status changes
  client/src/assets/ArtistsIcon.jsx
  client/src/assets/CancelIcon.jsx
  client/src/assets/ClockFilled.jsx
  client/src/assets/CustomOption.jsx
  client/src/assets/DeleteIcon.jsx
  client/src/assets/DollarBill.jsx
  client/src/assets/FilledOutCalendar.jsx
  client/src/assets/FilterIcon.jsx
  client/src/assets/LocationPin.jsx
  client/src/assets/PersonIcon.jsx
  client/src/assets/ProgramEmailIcon.jsx
  client/src/assets/ProgramsCalendarIcon.jsx
  client/src/assets/SessionsBookmark.jsx
  client/src/assets/TrashIcon.jsx
  client/src/assets/icons/cancelicon.svg
  client/src/components/programs/CancelSessionModal.jsx
  client/src/components/programs/DateRange.jsx
  client/src/components/programs/Program.jsx
  client/src/components/programs/ProgramComponents.jsx
  client/src/components/programs/WeeklyRepeatingSchedule.jsx
  package-lock.json
  server/routes/bookings.js
  server/routes/comments.js
  server/routes/invoices.js
  yarn.lock
Labels: Fix Needed, Fix Ready
