Repository ctc-uci/lpa, pull requests merged in 2025-02, with the labels that each got.

#66 54 creating program page
  client/package.json
  client/src/App.jsx
  client/src/assets/icons/ProgramIcons.jsx
  client/src/components/EventsTable.jsx
  client/src/components/programs/Program.jsx
  client/src/components/programs/ProgramComponents.jsx
  yarn.lock
Labels: Looks Good

#65 Edit program page & Navbar
  client/src/App.jsx
  client/src/assets/CalendarIcon.jsx
  client/src/assets/CancelIcon.jsx
  client/src/assets/ClockFilledIcon.jsx
  client/src/assets/CloseFilledIcon.jsx
  client/src/assets/DollarIcon.jsx
  client/src/assets/EmailIcon.jsx
  client/src/assets/InvoiceIcon.jsx
  client/src/assets/LocationIcon.jsx
  client/src/assets/NotificationsIcon.jsx
  client/src/assets/PlusFilledIcon.jsx
  client/src/assets/ProgramIcon.jsx
  client/src/assets/RepeatIcon.jsx
  client/src/assets/SettingsIcon.jsx
  client/src/assets/Vector.svg
  client/src/components/Navbar.jsx
  client/src/components/navbar/Navbar.css
  client/src/components/navbar/Navbar.jsx
  client/src/components/playground/Playground.jsx
  client/src/components/programs/EditProgram.css
  client/src/components/programs/EditProgram.jsx
  client/src/components/programs/Program.jsx
  server/routes/assignments.js
  server/routes/bookings.js
  server/routes/clients.js
  server/routes/comments.js
Labels: Looks Good

#64 Create invoice page
  client/src/App.jsx
  client/src/components/invoices/Invoice.jsx
  client/src/components/invoices/InvoiceComponents.jsx
  server/routes/comments.js
  server/routes/events.js
  server/routes/invoices.js
Labels: Looks Good

#63 Create Notifications Page
  client/src/App.jsx
  client/src/components/notifications/CalendarIcon.jsx
  client/src/components/notifications/Counter.jsx
  client/src/components/notifications/FilterButton.jsx
  client/src/components/notifications/FilterButton.module.css
  client/src/components/notifications/FilterIcon.jsx
  client/src/components/notifications/Notifications.jsx
  client/src/components/notifications/Notifications.module.css
  client/src/components/notifications/NotificationsComponents.jsx
  server/routes/invoices.js
Labels: Looks Good

#62 Creating home page
  client/index.html
  client/src/App.jsx
  client/src/assets/icons/actions.svg
  client/src/assets/icons/active.svg
  client/src/assets/icons/archive.svg
  client/src/assets/icons/calendar.svg
  client/src/assets/icons/cancel.svg
  client/src/assets/icons/clock.svg
  client/src/assets/icons/edit.svg
  client/src/assets/icons/filter.svg
  client/src/assets/icons/google-calendar.svg
  client/src/assets/icons/location.svg
  client/src/assets/icons/none.svg
  client/src/assets/icons/past.svg
  client/src/assets/icons/person.svg
  client/src/assets/icons/plus.svg
  client/src/assets/icons/program.svg
  client/src/assets/icons/search.svg
  client/src/components/AddClassModal.jsx
  client/src/components/home/HeaderRowComponent.jsx
  client/src/components/home/Home.css
  client/src/components/home/Home.jsx
  client/src/components/home/HomeComponents.jsx
  client/src/components/home/ProgramFiltersModal.jsx
  client/src/components/home/StatusIcon.jsx
  server/routes/events.js
  server/routes/programs.js
  server/routes/rooms.js
  server/src/app.js
Labels: Fix Ready

#78 Created total endpoint and settings skeleton
  client/src/App.jsx
  client/src/components/settings/Settings.jsx
  server/routes/invoices.js
Labels: Fix Ready

#79 70 login midfi and login flow
  client/src/App.jsx
  client/src/components/forgotpassword/ForgotPassword.jsx
  client/src/components/forgotpassword/ForgotPasswordSent.jsx
  client/src/components/login/ForgotPassword.jsx
  client/src/components/login/Login.jsx
  client/src/components/resetpassword/ResetPassword.jsx
  client/src/components/resetpassword/ResetPasswordSuccess.jsx
  client/src/components/signup/Signup.jsx
  client/src/components/signup/SignupRequested.jsx
Labels: Fix Ready

#80 72 single invoice page
  client/src/App.jsx
  client/src/components/invoices/EditInvoice.jsx
  client/src/components/invoices/EditInvoiceComponents.jsx
  client/src/components/invoices/EmailHistory.jsx
  client/src/components/invoices/InvoiceComponents.jsx
  client/src/components/invoices/SingleInvoice.jsx
  server/routes/assignments.js
  server/routes/comments.js
  server/routes/invoices.js
Labels: Fix Ready

#82 69 archived program page and delete restore functionality
  client/src/App.jsx
  client/src/assets/ArchiveIcon.jsx
  client/src/assets/icons/ProgramIcons.jsx
  client/src/components/home/HomeComponents.jsx
  client/src/components/programs/ArchivedPrograms.jsx
  client/src/components/programs/ProgramComponents.jsx
  server/routes/assignments.js
  server/routes/programs.js
Labels: Fix Needed

#83 67 implement notifications and email system
  client/package.json
  client/src/assets/icons/CkEmail.svg
  client/src/components/email/SendEmailButton.jsx
  client/src/components/navbar/Navbar.css
  client/src/components/navbar/Navbar.jsx
  client/src/components/notifications/Counter.jsx
  client/src/components/notifications/FilterButton.jsx
  client/src/components/notifications/FilterButton.module.css
  client/src/components/notifications/InboxTab.jsx
  client/src/components/notifications/Notifications.jsx
  client/src/components/notifications/Notifications.module.css
  client/src/components/notifications/NotificationsComponents.jsx
  client/src/components/playground/Playground.jsx
  server/.env.example
  server/Test.pdf
  server/common/transporter.ts
  server/package.json
  server/routes/email.js
  server/routes/invoices.js
  server/src/app.js
  yarn.lock
Labels: Fix Needed

#91 90 kaitlin sindhuja
  client/src/components/bookings/EditBooking.jsx
  client/src/components/programs/ProgramComponents.jsx
Labels: Looks Good
